# ===== DataSource =====
spring.datasource.url=jdbc:postgresql://localhost:5432/oripa_gacha
spring.datasource.username=postgres
spring.datasource.password=postgresss
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# ===== Encoding =====
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'
